/* Generated by tools/emit-gd-ctr.py from the retained .ctr, not the dictionary.
 * 144 readable requests at RAM 0x24000010..0x24002186.
 * Each comment gives its observed RAM address and section offset.
 * No inter-request alignment gaps occur in this image. The final implicit
 * string terminator ends at 0x24002186; the remaining two array bytes are
 * zero alignment padding through 0x24002188. These are metadata, not code.
 */
const char compile_time_requests[8568]
    __attribute__((used, aligned(4), section(".compile_time_request"))) =
    /* 0x24000010 / +0x0000 */
    "_DECL_STATIC_STR Stepper too far in past\0"
    /* 0x24000039 / +0x0029 */
    "DECL_COMMAND_FLAGS command_config_stepper 0 config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u\0"
    /* 0x240000b5 / +0x00a5 */
    "_DECL_STATIC_STR Invalid count parameter\0"
    /* 0x240000de / +0x00ce */
    "DECL_COMMAND_FLAGS command_queue_step 0 queue_step oid=%c interval=%u count=%hu add=%hi\0"
    /* 0x24000136 / +0x0126 */
    "DECL_COMMAND_FLAGS command_set_next_step_dir 0 set_next_step_dir oid=%c dir=%c\0"
    /* 0x24000185 / +0x0175 */
    "_DECL_STATIC_STR Can't reset time when stepper active\0"
    /* 0x240001bb / +0x01ab */
    "DECL_COMMAND_FLAGS command_reset_step_clock 0 reset_step_clock oid=%c clock=%u\0"
    /* 0x2400020a / +0x01fa */
    "_DECL_ENCODER stepper_position oid=%c pos=%i\0"
    /* 0x24000237 / +0x0227 */
    "DECL_COMMAND_FLAGS command_stepper_get_position 0 stepper_get_position oid=%c\0"
    /* 0x24000285 / +0x0275 */
    "DECL_COMMAND_FLAGS command_stepper_stop_on_trigger 0 stepper_stop_on_trigger oid=%c trsync_oid=%c\0"
    /* 0x240002e7 / +0x02d7 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs stepper_shutdown\0"
    /* 0x2400031d / +0x030d */
    "_DECL_STATIC_STR Command parser error\0"
    /* 0x24000343 / +0x0333 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs sendf_shutdown\0"
    /* 0x24000377 / +0x0367 */
    "_DECL_STATIC_STR Message encode error\0"
    /* 0x2400039d / +0x038d */
    "_DECL_STATIC_STR Invalid command\0"
    /* 0x240003be / +0x03ae */
    "_DECL_STATIC_STR Timer too close\0"
    /* 0x240003df / +0x03cf */
    "_DECL_STATIC_STR Shutdown cleared when not shutdown\0"
    /* 0x24000413 / +0x0403 */
    "_DECL_ENCODER GDMainboard close=%hu Close_num=%hu Temp_waketime=%hu\0"
    /* 0x24000457 / +0x0447 */
    "_DECL_ENCODER is_shutdown static_string_id=%hu\0"
    /* 0x24000486 / +0x0476 */
    "_DECL_ENCODER starting\0"
    /* 0x2400049d / +0x048d */
    "_DECL_STATIC_STR sentinel timer called\0"
    /* 0x240004c4 / +0x04b4 */
    "_DECL_ENCODER shutdown clock=%u static_string_id=%hu\0"
    /* 0x240004f9 / +0x04e9 */
    "_DECL_CALLLIST ctr_run_initfuncs alloc_init\0"
    /* 0x24000525 / +0x0515 */
    "_DECL_STATIC_STR alloc_chunk failed\0"
    /* 0x24000549 / +0x0539 */
    "_DECL_STATIC_STR Move queue overflow\0"
    /* 0x2400056e / +0x055e */
    "_DECL_STATIC_STR Invalid move request size\0"
    /* 0x24000599 / +0x0589 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs move_reset\0"
    /* 0x240005c9 / +0x05b9 */
    "_DECL_STATIC_STR Invalid oid type\0"
    /* 0x240005eb / +0x05db */
    "_DECL_STATIC_STR Can't assign oid\0"
    /* 0x2400060d / +0x05fd */
    "_DECL_STATIC_STR oids already allocated\0"
    /* 0x24000635 / +0x0625 */
    "DECL_COMMAND_FLAGS command_allocate_oids 0 allocate_oids count=%c\0"
    /* 0x24000677 / +0x0667 */
    "_DECL_ENCODER config is_config=%c crc=%u is_shutdown=%c move_count=%hu\0"
    /* 0x240006be / +0x06ae */
    "DECL_COMMAND_FLAGS command_get_config 0x01 get_config\0"
    /* 0x240006f4 / +0x06e4 */
    "DECL_COMMAND_FLAGS command_finalize_config 0 finalize_config crc=%u\0"
    /* 0x24000738 / +0x0728 */
    "_DECL_STATIC_STR config_reset only available when shutdown\0"
    /* 0x24000773 / +0x0763 */
    "_DECL_ENCODER clock clock=%u\0"
    /* 0x24000790 / +0x0780 */
    "DECL_COMMAND_FLAGS command_get_clock 0x01 get_clock\0"
    /* 0x240007c4 / +0x07b4 */
    "_DECL_ENCODER uptime high=%u clock=%u\0"
    /* 0x240007ea / +0x07da */
    "DECL_COMMAND_FLAGS command_get_uptime 0x01 get_uptime\0"
    /* 0x24000820 / +0x0810 */
    "DECL_CONSTANT STATS_SUMSQ_BASE +0x00000100\0"
    /* 0x2400084b / +0x083b */
    "_DECL_ENCODER stats count=%u sum=%u sumsq=%u\0"
    /* 0x24000878 / +0x0868 */
    "_DECL_STATIC_STR Command request\0"
    /* 0x24000899 / +0x0889 */
    "DECL_COMMAND_FLAGS command_emergency_stop 0x01 emergency_stop\0"
    /* 0x240008d7 / +0x08c7 */
    "DECL_COMMAND_FLAGS command_clear_shutdown 0x01 clear_shutdown\0"
    /* 0x24000915 / +0x0905 */
    "_DECL_ENCODER identify_response offset=%u data=%.*s\0"
    /* 0x24000949 / +0x0939 */
    "DECL_COMMAND_FLAGS command_identify 0x01 identify offset=%u count=%c\0"
    /* 0x2400098e / +0x097e */
    "_DECL_ENCODER pa_value value=%u\0"
    /* 0x240009ae / +0x099e */
    "DECL_COMMAND_FLAGS command_get_pa 0 get_emcu_pa_value\0"
    /* 0x240009e4 / +0x09d4 */
    "DECL_COMMAND_FLAGS command_pa_action 0 pa_action action=%u pc=%u\0"
    /* 0x24000a25 / +0x0a15 */
    "DECL_COMMAND_FLAGS command_remove_peel 0 remove_peel action=%u\0"
    /* 0x24000a64 / +0x0a54 */
    "_DECL_ENCODER mcu_version year=%u date=%u version=%u\0"
    /* 0x24000a99 / +0x0a89 */
    "DECL_COMMAND_FLAGS command_get_mcu_version 0 get_mcu_version\0"
    /* 0x24000ad6 / +0x0ac6 */
    "_DECL_ENCODER param_value value=%u reserve=%u\0"
    /* 0x24000b04 / +0x0af4 */
    "DECL_COMMAND_FLAGS command_get_basic_param 0 get_basic_param num=%u\0"
    /* 0x24000b48 / +0x0b38 */
    "_DECL_STATIC_STR Already finalized\0"
    /* 0x24000b6b / +0x0b5b */
    "_DECL_STATIC_STR alloc_chunks failed\0"
    /* 0x24000b90 / +0x0b80 */
    "DECL_COMMAND_FLAGS command_config_digital_out 0 config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u\0"
    /* 0x24000c0b / +0x0bfb */
    "_DECL_STATIC_STR Can not set soft pwm cycle ticks while updates pending\0"
    /* 0x24000c53 / +0x0c43 */
    "DECL_COMMAND_FLAGS command_set_digital_out_pwm_cycle 0 set_digital_out_pwm_cycle oid=%c cycle_ticks=%u\0"
    /* 0x24000cba / +0x0caa */
    "_DECL_STATIC_STR Scheduled digital out event will exceed max_duration\0"
    /* 0x24000d00 / +0x0cf0 */
    "DECL_COMMAND_FLAGS command_queue_digital_out 0 queue_digital_out oid=%c clock=%u on_ticks=%u\0"
    /* 0x24000d5d / +0x0d4d */
    "_DECL_STATIC_STR update_digital_out not valid with active queue\0"
    /* 0x24000d9d / +0x0d8d */
    "DECL_COMMAND_FLAGS command_update_digital_out 0 update_digital_out oid=%c value=%c\0"
    /* 0x24000df0 / +0x0de0 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs digital_out_shutdown\0"
    /* 0x24000e2a / +0x0e1a */
    "DECL_COMMAND_FLAGS command_set_digital_out 0 set_digital_out pin=%u value=%c\0"
    /* 0x24000e77 / +0x0e67 */
    "_DECL_STATIC_STR Missed scheduling of next digital out event\0"
    /* 0x24000eb4 / +0x0ea4 */
    "_DECL_STATIC_STR Scheduled digital out event will exceed max_duration\0"
    /* 0x24000efa / +0x0eea */
    "_DECL_ENCODER debug_result val=%u\0"
    /* 0x24000f1c / +0x0f0c */
    "DECL_COMMAND_FLAGS command_debug_read 0x01 debug_read order=%c addr=%u\0"
    /* 0x24000f63 / +0x0f53 */
    "DECL_COMMAND_FLAGS command_debug_write 0x01 debug_write order=%c addr=%u val=%u\0"
    /* 0x24000fb3 / +0x0fa3 */
    "_DECL_ENCODER pong data=%*s\0"
    /* 0x24000fcf / +0x0fbf */
    "DECL_COMMAND_FLAGS command_debug_ping 0x01 debug_ping data=%*s\0"
    /* 0x2400100e / +0x0ffe */
    "DECL_COMMAND_FLAGS command_debug_nop 0x01 debug_nop\0"
    /* 0x24001042 / +0x1032 */
    "DECL_COMMAND_FLAGS command_config_endstop 0 config_endstop oid=%c pin=%c pull_up=%c\0"
    /* 0x24001096 / +0x1086 */
    "DECL_COMMAND_FLAGS command_endstop_home 0 endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c\0"
    /* 0x24001138 / +0x1128 */
    "_DECL_ENCODER endstop_state oid=%c homing=%c next_clock=%u pin_value=%c\0"
    /* 0x24001180 / +0x1170 */
    "DECL_COMMAND_FLAGS command_endstop_query_state 0 endstop_query_state oid=%c\0"
    /* 0x240011cc / +0x11bc */
    "DECL_INITIAL_PINS \"\"\0"
    /* 0x240011e1 / +0x11d1 */
    "_DECL_CALLLIST ctr_run_initfuncs initial_pins_setup\0"
    /* 0x24001215 / +0x1205 */
    "DECL_COMMAND_FLAGS command_config_trsync 0 config_trsync oid=%c\0"
    /* 0x24001255 / +0x1245 */
    "_DECL_STATIC_STR Can't add signal that is already active\0"
    /* 0x2400128e / +0x127e */
    "DECL_COMMAND_FLAGS command_trsync_start 0 trsync_start oid=%c report_clock=%u report_ticks=%u expire_reason=%c\0"
    /* 0x240012fd / +0x12ed */
    "DECL_COMMAND_FLAGS command_trsync_set_timeout 0 trsync_set_timeout oid=%c clock=%u\0"
    /* 0x24001350 / +0x1340 */
    "DECL_COMMAND_FLAGS command_trsync_trigger 0 trsync_trigger oid=%c reason=%c\0"
    /* 0x2400139c / +0x138c */
    "_DECL_CALLLIST ctr_run_taskfuncs trsync_task\0"
    /* 0x240013c9 / +0x13b9 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs trsync_shutdown\0"
    /* 0x240013fe / +0x13ee */
    "_DECL_ENCODER trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u\0"
    /* 0x2400144a / +0x143a */
    "DECL_COMMAND_FLAGS command_config_analog_in 0 config_analog_in oid=%c pin=%u\0"
    /* 0x24001497 / +0x1487 */
    "DECL_COMMAND_FLAGS command_query_analog_in 0 query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u min_value=%hu max_value=%hu range_check_count=%c\0"
    /* 0x24001543 / +0x1533 */
    "_DECL_ENCODER analog_in_state oid=%c next_clock=%u value=%hu\0"
    /* 0x24001580 / +0x1570 */
    "_DECL_CALLLIST ctr_run_taskfuncs analog_in_task\0"
    /* 0x240015b0 / +0x15a0 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs analog_in_shutdown\0"
    /* 0x240015e8 / +0x15d8 */
    "_DECL_STATIC_STR ADC out of range\0"
    /* 0x2400160a / +0x15fa */
    "DECL_ENUMERATION stepper stepper_x +0x00000000\0"
    /* 0x24001639 / +0x1629 */
    "DECL_ENUMERATION stepper stepper_y +0x00000001\0"
    /* 0x24001668 / +0x1658 */
    "DECL_ENUMERATION stepper stepper_z +0x00000002\0"
    /* 0x24001697 / +0x1687 */
    "DECL_ENUMERATION stepper extruder +0x00000003\0"
    /* 0x240016c5 / +0x16b5 */
    "_DECL_CALLLIST ctr_run_initfuncs mclib_init\0"
    /* 0x240016f1 / +0x16e1 */
    "DECL_COMMAND_FLAGS command_config_mclib 0 config_mclib oid=%c stepper=%u rs=%u ls=%u km=%u\0"
    /* 0x2400174c / +0x173c */
    "DECL_COMMAND_FLAGS command_mclib_config_microstep 0 mclib_config_microstep oid=%c interpolate=%c mstep=%u\0"
    /* 0x240017b6 / +0x17a6 */
    "DECL_COMMAND_FLAGS command_mclib_config_stalldetect 0 mclib_config_stalldetect oid=%c stallthrs=%u\0"
    /* 0x24001819 / +0x1809 */
    "DECL_COMMAND_FLAGS command_mclib_set_current 0 mclib_set_current oid=%c run_current=%u hold_current=%u\0"
    /* 0x24001880 / +0x1870 */
    "DECL_COMMAND_FLAGS command_mclib_set_pid_params 0 mclib_set_pid_params oid=%c kp=%u ki=%u\0"
    /* 0x240018da / +0x18ca */
    "DECL_COMMAND_FLAGS command_mclib_identify_motor 0 mclib_identify_motor oid=%c umax=%u umin=%u\0"
    /* 0x24001938 / +0x1928 */
    "DECL_COMMAND_FLAGS command_mclib_set_resonance_damp 0 mclib_set_resonance_damp oid=%c tdx=%c amp=%u phase1=%u phase2=%u\0"
    /* 0x240019b0 / +0x19a0 */
    "_DECL_STATIC_STR Max of 8 buttons\0"
    /* 0x240019d2 / +0x19c2 */
    "DECL_COMMAND_FLAGS command_config_buttons 0 config_buttons oid=%c button_count=%c\0"
    /* 0x24001a24 / +0x1a14 */
    "_DECL_STATIC_STR Set button past maximum button count\0"
    /* 0x24001a5a / +0x1a4a */
    "DECL_COMMAND_FLAGS command_buttons_add 0 buttons_add oid=%c pos=%c pin=%u pull_up=%c\0"
    /* 0x24001aaf / +0x1a9f */
    "_DECL_STATIC_STR Invalid buttons retransmit count\0"
    /* 0x24001ae1 / +0x1ad1 */
    "DECL_COMMAND_FLAGS command_buttons_query 0 buttons_query oid=%c clock=%u rest_ticks=%u retransmit_count=%c invert=%c\0"
    /* 0x24001b56 / +0x1b46 */
    "DECL_COMMAND_FLAGS command_buttons_ack 0 buttons_ack oid=%c count=%c\0"
    /* 0x24001b9b / +0x1b8b */
    "_DECL_ENCODER buttons_state oid=%c ack_count=%c state=%*s\0"
    /* 0x24001bd5 / +0x1bc5 */
    "_DECL_CALLLIST ctr_run_taskfuncs buttons_task\0"
    /* 0x24001c03 / +0x1bf3 */
    "DECL_CONSTANT SERIAL_BAUD +0x00038400\0"
    /* 0x24001c29 / +0x1c19 */
    "DECL_CONSTANT RECEIVE_WINDOW +0x00000180\0"
    /* 0x24001c52 / +0x1c42 */
    "_DECL_CALLLIST ctr_run_taskfuncs console_task\0"
    /* 0x24001c80 / +0x1c70 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs clear_active_irq\0"
    /* 0x24001cb6 / +0x1ca6 */
    "DECL_COMMAND_FLAGS command_reset 0x01 reset\0"
    /* 0x24001ce2 / +0x1cd2 */
    "DECL_CONSTANT CLOCK_FREQ +0x23C34600\0"
    /* 0x24001d07 / +0x1cf7 */
    "_DECL_CALLLIST ctr_run_shutdownfuncs timer_reset\0"
    /* 0x24001d38 / +0x1d28 */
    "_DECL_CALLLIST ctr_run_initfuncs timer_cnt_init\0"
    /* 0x24001d68 / +0x1d58 */
    "DECL_ARMCM_IRQ SysTick_Handler -0x00000001\0"
    /* 0x24001d93 / +0x1d83 */
    "_DECL_CALLLIST ctr_run_taskfuncs timer_task\0"
    /* 0x24001dbf / +0x1daf */
    "_DECL_STATIC_STR Rescheduled timer in the past\0"
    /* 0x24001dee / +0x1dde */
    "_DECL_CALLLIST ctr_run_taskfuncs watchdog_reset\0"
    /* 0x24001e1e / +0x1e0e */
    "_DECL_CALLLIST ctr_run_initfuncs watchdog_init\0"
    /* 0x24001e4d / +0x1e3d */
    "DECL_ENUMERATION_RANGE pin PA0 +0x00000000 +0x00000010\0"
    /* 0x24001e84 / +0x1e74 */
    "DECL_ENUMERATION_RANGE pin PB0 +0x00000010 +0x00000010\0"
    /* 0x24001ebb / +0x1eab */
    "DECL_ENUMERATION_RANGE pin PC0 +0x00000020 +0x00000010\0"
    /* 0x24001ef2 / +0x1ee2 */
    "DECL_ENUMERATION_RANGE pin PD0 +0x00000030 +0x00000010\0"
    /* 0x24001f29 / +0x1f19 */
    "DECL_ENUMERATION_RANGE pin PE0 +0x00000040 +0x00000010\0"
    /* 0x24001f60 / +0x1f50 */
    "DECL_ENUMERATION_RANGE pin PF0 +0x00000050 +0x00000010\0"
    /* 0x24001f97 / +0x1f87 */
    "DECL_ENUMERATION_RANGE pin PG0 +0x00000060 +0x00000010\0"
    /* 0x24001fce / +0x1fbe */
    "DECL_ENUMERATION_RANGE pin PH0 +0x00000070 +0x00000010\0"
    /* 0x24002005 / +0x1ff5 */
    "DECL_ENUMERATION_RANGE pin PJ0 +0x00000090 +0x00000010\0"
    /* 0x2400203c / +0x202c */
    "_DECL_STATIC_STR Not an output pin\0"
    /* 0x2400205f / +0x204f */
    "_DECL_STATIC_STR Not a valid input pin\0"
    /* 0x24002086 / +0x2076 */
    "DECL_CONSTANT ADC_MAX +0x00000FFF\0"
    /* 0x240020a8 / +0x2098 */
    "DECL_ENUMERATION pin ADC_TEMPERATURE +0x000000FE\0"
    /* 0x240020d9 / +0x20c9 */
    "_DECL_STATIC_STR Not a valid ADC pin\0"
    /* 0x240020fe / +0x20ee */
    "DECL_CONSTANT_STR RESERVE_PINS_serial PA9,P10\0"
    /* 0x2400212c / +0x211c */
    "DECL_ARMCM_IRQ USART0_IRQHandler +0x00000025\0"
    /* 0x24002159 / +0x2149 */
    "_DECL_CALLLIST ctr_run_initfuncs serial_init"
    ;

_Static_assert(sizeof(compile_time_requests) == 8568, "retained .ctr span");
