#!/usr/bin/env python3
"""Emit readable retained mainBoardGD .ctr metadata and verify compiled RAM bytes.

  python3 tools/emit-gd-ctr.py
  python3 tools/emit-gd-ctr.py --check --verify --report work/mainBoardGD-ctr.json

The validated 144 retained requests, NOT a regenerated dictionary, supply the
strings and order. Verification compiles the checked-in C and compares its
complete section (including alignment zeros) to scatter-decompressed stock.
This is initialized metadata data, never executable coverage or a firmware link.
CASES exposes (symbol, RAM address, full size) for partial integration.
"""
import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'mcu/mainBoardGD/recovered/compile_time_requests.c'
RAM = 0x24000000
START, REQUEST_END, END = 0x24000010, 0x24002186, 0x24002188
CASES = [('compile_time_requests', START, END - START)]
SECTION = '.compile_time_request'
COMPATIBILITY_FLAGS = ['-mllvm', '-arm-promote-constant', '-fno-unroll-loops',
                       '-falign-loops=4', '-mllvm', '-enable-shrink-wrap=false', '-fno-builtin']


def module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result


def quote(text):
    """C ASCII string syntax; avoid JSON's invalid C \u0009-style escapes."""
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"').replace('\t', '\\t') + '"'


def emit(requests, data):
    if len(requests) != 144 or requests[0]['address'] != START:
        raise ValueError('unexpected retained request count/start')
    lines = [
        '/* Generated by tools/emit-gd-ctr.py from the retained .ctr, not the dictionary.',
        ' * 144 readable requests at RAM 0x24000010..0x24002186.',
        ' * Each comment gives its observed RAM address and section offset.',
        ' * No inter-request alignment gaps occur in this image. The final implicit',
        ' * string terminator ends at 0x24002186; the remaining two array bytes are',
        ' * zero alignment padding through 0x24002188. These are metadata, not code.',
        ' */',
        'const char compile_time_requests[8568]',
        '    __attribute__((used, aligned(4), section(".compile_time_request"))) =',
    ]
    manifest = []
    cursor = START
    for index, request in enumerate(requests):
        address, text = request['address'], request['text']
        raw = text.encode('ascii') + b'\0'
        if address != cursor or data[address - RAM:address - RAM + len(raw)] != raw:
            raise ValueError('noncontiguous or inconsistent request at %#x' % address)
        if not text or any(ord(c) != 9 and not 32 <= ord(c) <= 126 for c in text):
            raise ValueError('unsupported control character in retained request')
        lines.append('    /* 0x%08x / +0x%04x */' % (address, address - START))
        literal = quote(text)
        if index + 1 != len(requests):
            literal = literal[:-1] + '\\0"'
        lines.append('    ' + literal)
        manifest.append(dict(address=address, offset=address - START,
                             size=len(raw), text=text))
        cursor += len(raw)
    if cursor != REQUEST_END or data[cursor - RAM:END - RAM] != bytes(END - cursor):
        raise ValueError('unexpected final request extent/alignment')
    lines += ['    ;', '', '_Static_assert(sizeof(compile_time_requests) == 8568, "retained .ctr span");', '']
    return '\n'.join(lines), manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='check deterministic C without writing it')
    parser.add_argument('--verify', action='store_true', help='compile/link and compare complete data')
    parser.add_argument('--cc', default=os.environ.get('MCU_GD_CC'))
    parser.add_argument('--source', type=Path, default=SOURCE)
    parser.add_argument('--build-dir', type=Path, default=ROOT / 'work/mainBoardGD-ctr')
    parser.add_argument('--report', type=Path)
    args = parser.parse_args()
    tc = module('gd_toolchain', ROOT / 'tools/check-gd-toolchain.py')
    ex = module('gd_extractor', ROOT / 'tools/extract-gd-generated.py')
    image = tc.STOCK.read_bytes()
    if hashlib.md5(image).hexdigest() != tc.STOCK_MD5:
        raise ValueError('unsupported mainBoardGD stock image')
    metadata, _, data = ex.extract(image)
    rendered, requests = emit(metadata['compile_time_requests'], data)
    source = args.source.resolve()
    errors, results, commands = [], [], []
    if args.check:
        deterministic = source.is_file() and source.read_text() == rendered
        if not deterministic:
            errors.append('checked-in C differs from deterministic retained-request emission')
    else:
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_text(rendered)
        deterministic = True
    report = dict(schema_version=1,
                  scope='retained compile-time request initialized RAM data; not executable code',
                  image_sha256=hashlib.sha256(image).hexdigest(), stock_md5=tc.STOCK_MD5,
                  request_count=len(requests), request_bytes=REQUEST_END - START,
                  alignment_bytes=END - REQUEST_END, requests=requests,
                  source_emission_matches=deterministic, results=results, commands=commands,
                  errors=errors)
    if args.verify:
        try:
            cc = tc.compiler_path(args.cc)
            out = args.build_dir.resolve()
            out.mkdir(parents=True, exist_ok=True)
            obj, elf, script = out / 'ctr.o', out / 'ctr.elf', out / 'ctr.ld'
            flags = [*tc.FLAGS, *COMPATIBILITY_FLAGS]
            command = [str(cc), *flags, '-c', str(source), '-o', str(obj)]
            commands.append(command)
            subprocess.run(command, check=True)
            script.write_text('SECTIONS {\n  .compile_time_request 0x24000010 : '
                              '{ KEEP(*(.compile_time_request)) }\n}\n')
            command = [str(cc), *tc.FLAGS[:4], '-nostdlib', '-Wl,--entry=compile_time_requests',
                       '-Wl,-T,' + str(script), str(obj), '-o', str(elf)]
            commands.append(command)
            subprocess.run(command, check=True)
            reader = module('gd_motor', ROOT / 'tools/check-gd-motor.py')
            address, actual = reader.section(elf, SECTION)
            expected = data[START - RAM:END - RAM]
            exact = address == START and actual == expected
            results.append(dict(name='compile_time_requests', kind='initialized_data',
                                address=START, actual_address=address, size=len(expected),
                                actual_size=len(actual), exact=exact,
                                matching_bytes=sum(a == b for a, b in zip(actual, expected)),
                                expected_sha256=hashlib.sha256(expected).hexdigest(),
                                actual_sha256=hashlib.sha256(actual).hexdigest()))
            report.update(compiler=str(cc), compiler_sha256=hashlib.sha256(cc.read_bytes()).hexdigest(),
                          compiler_version=subprocess.check_output([str(cc), '--version'], text=True).strip(),
                          flags=flags)
            if not exact:
                errors.append('compiled .compile_time_request differs from expanded stock RAM')
            print('retained .ctr: %d/%d bytes, %s' %
                  (results[-1]['matching_bytes'], len(expected), 'EXACT' if exact else 'DIFF'))
        except (ValueError, OSError, subprocess.CalledProcessError) as error:
            errors.append('verification failed: ' + str(error))
    inputs = [source, Path(__file__).resolve(), ROOT / 'tools/extract-gd-generated.py',
              ROOT / 'tools/scatterload.py', ROOT / 'tools/check-gd-toolchain.py',
              ROOT / 'tools/check-gd-motor.py']
    report['source_sha256'] = {
        str(p.relative_to(ROOT)) if p.is_relative_to(ROOT) else str(p):
        hashlib.sha256(p.read_bytes()).hexdigest() for p in inputs if p.is_file()}
    report['all_requested_gates_passed'] = not errors
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2) + '\n')
    for error in errors:
        print(error)
    print('144 retained requests; 8566 string bytes + 2 alignment zeros; '
          + ('source emission verified.' if deterministic else 'source emission differs.'))
    return int(bool(errors))


if __name__ == '__main__':
    raise SystemExit(main())
